### ISSUE TITLE
Merge sediment code into iHAMOCC

### ISSUE THREAD

**Issue by TomasTorsvik** [NorESMhub/BLOM#18]
@mvhulten @JorgSchwinger @matsbn 
I would like to merge the sediment code written by Marco, into the iHAMOCC source code. I was able to convert his original mercurial repository into git and import it to gitHub (https://github.com/TomasTorsvik-work/hamocc_sediment_legacy). I think the next step should be to create a feature branch in the BLOM repository and try to merge in incremental steps, but I'm not yet sure how I will proceed with this. Will probably tinker a bit in my personal repo before I start pushing anything. Let me know if you have any ideas/suggestions about this work.

**Comment by JorgSchwinger** [comment]
Hi Thomas,

good to hear that you are planning to do this. Some considerations:

I am pretty sure that an automatic merge will not work for any of the code (as you already suspect), since it is based on a pretty old code version and a lot of development has been done in between. I think you could proceed as follows:

1. implement the updated actual sediment routines only (powach, powadi, dipowa, sedshi, bodensed, mo_bodensed), and test whether we can get bit-identical results. I have made a 2-degree test case that fits in the development-queue on fram, and can be compared to a CMIP6-OMIP simulation.

2. Implement the save/replay of the fluxes to the sediment. Since there have been changes to hamocc_step (and many others), this has to be done with care. I suggest, for the time being, to omit all the changes that facilitate output of the sediment code when in "sediment only" mode. In my opinion we don't need this capability (urgently) and it complicates the merging. We just have to make sure that the saved climatology of fluxes to the sediment is correct (this should be tested again).

We probably need to discuss one or the other thing, but the first step should be relatively straight forward.

**Comment by JorgSchwinger** [comment]
I forgot to mention: before making a new branch, please wait until the NorESM2 release is ready. Mats and I are still working on a better structure for the input data, which will be the last code update before the release. I suggest we take the NorESM2 release as a starting point for new developments.

**Comment by TomasTorsvik** [comment]
@JorgSchwinger 
OK, I will wait with the feature branch. I can do some testing in my fork for now. Do you have a estimate for when the NorESM2 release will be ready?

**Comment by JorgSchwinger** [comment]
Release of NorESM2 is planned to be June 15 as far as I know

**Comment by TomasTorsvik** [comment]
I think it will be difficult to integrate the sediment burst-coupling method into BLOM/iHAMOCC, as it is designed to run in an alternating online-offline mode with the full model system. Therefore I think the best solution for now is to keep this code in a separate long-lived feature branch and update it when new BLOM/iHAMOCC versions are released.

**Comment by mvhulten** [comment]
Almost all code can be excluded from compilation by a preprocessor directive (cpp key), but below I will assume it is always compiled with the code because cpp keys are to be avoided.  Furthermore I tried to code it as independent as possible from the rest of the code (given my general approach).  Nonetheless, you're right that the burst coupling (online/offline mode) exists in the full model system; moreover, the stand-alone sediment is a subloop within a single iHAMOCC step.

On the one hand, because of this approach (badly chosen or not) iHAMOCC always has two possible modes.  If there is a bug (introduced) in determining the mode, this would be critical, which makes your proposal worth considering.  On the other hand, updating this separate feature branch with each new BLOM/iHAMOCC version would be a pain-in-the-sth on itself.

**Comment by TomasTorsvik** [comment]
I hope the sediment code can be fully merged at some point, but I think it is best to do this in multiple steps. First goal is to get a version that is synced as much as possible with the most recent BLOM version.

**Comment by JorgSchwinger** [comment]
Hi everyone,

it would be really desirable to have an accelerated sediment spin-up as a standard procedure during a model spin up, where "standard" would mean that it is part of the main model branch (master).

What complicates things in the current situation is that Marco's sediment code can write output. As far as I understand, this requires changing a lot of files _outside_ the sediment code (also in BLOM/phys). While this might be useful for testing, in my opinion, we do not need this capability. The correctness of the code could be checked by other means. The sediment-spin-up would then only (i) record boundary conditions during x years of normal integration, (ii) do y years of offline sediment using the boundary conditions from (i). Step (ii) would not record any model output, nor advance the model calendar. (iii) repeat as often as needed/possible. The numbers x and y would be namelist input, and hopefully from Marco's study one could recommend reasonable settings for those. 

Maybe we can discuss this in a physical (or online) meeting some time in August?

**Comment by TomasTorsvik** [comment]
I'm back in Bergen on August 17. It would be good if we can discuss merging of the sediment model code during the week Aug. 17-21. I'm available all days. If it's just the 3 of us, I suppose we could meet in person, if we find a suitable meeting room.

**Comment by TomasTorsvik** [comment]
@JorgSchwinger 
We will probably go for a different solution, so I mark this as "wontfix". Should I close this issue now?

**Comment by JorgSchwinger** [comment]
Yes, I think this can be closed
