### ISSUE TITLE
Differences between current master and reference norESM2.0.5 run

### ISSUE THREAD

**Issue by TomasTorsvik** [NorESMhub/BLOM#183]
Hi,
I was testing a standard 1 year `NOINYOC_T62_tn21` setup on BETZY with the latest BLOM/iHAMOCC master (ce2fcd87e) and I see some differences in the output when I compare with a reference `noresm2.0.5` run. Specifically for the monthly output file `*.blom.hm.0001-12.nc` the bit-reproducible test fails for the variables `wflx : vertical mass flux`, `wflx2 : vertical mass flux squared`, `bfsq : buoyancy frequency squared`, and `bfsqlvl`. Somehow, the other fields (both physics and BGC output) does not seem to be affected.

1. Does anyone else see the same change between our current `master` and the reference `noresm2.0.5` in your runs, or could it be something with my setup?
2. Is this an expected side effect of changing the vertical grid structure?
3. If confirmed, can we still claim backwards comparability with CMIP6 for our current `master` branch?

**Comment by TomasTorsvik** [comment]
I checked some earlier commits. The change seems to be related to the introduction of the hybrid vertical scheme. I get bit-identical results with `noresm2.0.5` for the last commit before the hybrid verical scheme was introduced (0d40e31) and a change in the 4 variables mentioned above with the merge commit for the hybrid vertical scheme (9e6bd6b).

**Comment by matsbn** [comment]
I would say these are expected differences in diagnostic fields. I cannot recall exactly where the change happened, but for buoyancy frequency squared I think it is because we now compute buoyancy frequency for the lowermost interface which is not used prognostically in isopycnic mode, but appears as a difference in the diagnostics. I can look further into the wflx, but believe it was due to some initialisation or parallelisation bug that only impacted diagnostics. All of these are rarely used diagnostic fields and I am not sure they are CMORized at all. So I would say that for all practical purposes, master is still backward compatible. Still, I think any change in diagnostics should be mentioned in a pull request, so here there is room for improvement.

**Comment by TomasTorsvik** [comment]
Thanks @matsbn , I guess this should be OK then. I think we should make a note of this in the release notes when we make the next release of BLOM/iHAMOCC, and make sure that this information is also included in the next NorESM release notes. I suggest we keep this issue open for the time being as a reminder, unless there is some better way to pin issues to an upcoming release.
