### ISSUE TITLE
License for BLOM

### ISSUE THREAD

**Issue by TomasTorsvik** [NorESMhub/BLOM#2]
It would be useful to clarify the license for BLOM. Assuming we are free to chose whatever license, I would suggest (having consulted with Marco) to go for either a GNU Lesser General Public License v3.0 (lgpl-3.0) or an Apache license 2.0 (apache-2.0).

**Comment by matsbn** [comment]
We discussed the licence a bit at the hackathon and I really appreciate your input @TomasTorsvik. The Apache licence require a copyright notice (Copyright [yyyy] [name of copyright owner]) and selecting an appropriate copyright owner is challenging since BLOM is a collaborative effort. The copyright notice is also a challenge with the MIT licence that we considered during the hackathon. The MIT licence is also very permissive allowing derived work in closed source projects. I agree LGPL v3 is a good suggestion, requiring derived work to remain open source (except when linking in libraries) and it seems a copyright owner must not be stated. MOM6 is using LGPL v3. CESM is now incorporating MOM6, and although CESM is open source, I am not sure the CESM licence is actually compatible with LGPL. That is maybe the only drawback with LGPL (or GPL), that compatibility with licences of derived work seems limited (although the derived work is open source).

**Comment by mvhulten** [comment]
You [need](https://fsfe.org/freesoftware/basics/who-owns-free-software.html) copyright to licence a work.  By default, the (legal) person who wrote the work has the copyright over the work.  For clarity it should be stated who this is.  This person can assign this copyright to another (legal) person.  When we signed our work contract, we probably signed away all copyright over our works to the organisation.  There are agreements, however, at most research facilities (at least UiB, LSCE and KNMI where I have worked and checked this) that you are allowed to publish under a free software licence.

We could use in the copyright notice as the name of the copyright holder *the BLOM team* or *the NorESM development team*, as many free software projects do.  We don't have such legal entity, and from this point I am not certain of the situation, but I think it is as follows.  The *de facto* authors of BLOM are Mats, Joerg, me and so on; *de jure* it are the respective organisations.  In any case, *the BLOM team* would be a label that includes all relevant legal constituents.  From the commits it is often clear who did what part of the work, but we should not fully rely on that because sometimes someone else commits large code developments of someone else (e.g. when including from a unrelated repository, and/or doing complicated, thus manual, merging).  Because of this (and other reasons) programmers should add a copyright statement in every source file they change or add.  [This and more](https://www.gnu.org/licenses/gpl-howto.html) should be done.

**Comment by TomasTorsvik** [comment]
If compatibility with derived work is the main concern, one could also consider the Mozilla Public License 2.0 (mpl-2.0). This includes weak copyleft conditions, somewhat similar to LGPL, but with less restrictions on the licensing of the derived work (at least to my understanding), see section 3.3 (https://choosealicense.com/licenses/mpl-2.0/ ). Maybe it would make sense to ask advice from someone who is more knowledgable about legal issues concerning licenses? Unfortunately, I don't have any suggestion who this might be.

**Comment by matsbn** [comment]
Thanks for you thoughts and information regarding copyright notice, @mvhulten. Regarding similar licensing issues for the new [NorESM](https://github.com/NorESMhub/NorESM) repository, Michael Schulz will ask for legal advise from a MET lawyer. I hope that also can help clarify how to proceed with the BLOM licence.
