### ISSUE TITLE
Fix pnetcdf issues in recent iHAMOCC updates

### ISSUE THREAD

**Issue by TomasTorsvik** [NorESMhub/BLOM#207]
It seems some of our recent updates in iHAMOCC are not compatible with using pnetcdf (see [NoRESM issue 385](https://github.com/NorESMhub/NorESM/issues/385). We should fix this for the NorESM2.0.6 release.

**Comment by jmaerz** [comment]
Hi Tomas, since the `PNETCDF` issue on betzy https://github.com/NorESMhub/cime/pull/34 is older than the commit with the explicit use statements: can you confirm that the problem was present before already (on betzy)?  If so, potentially a two step approach would help: first going to fix issues connected to the explicit use statements (I assume some `use` statements could be missing) for the machine, Dirk is working on (maybe he could share the run-recipe there), and afterward we could head to betzy.

**Comment by TomasTorsvik** [comment]
Hi Jöran, my understanding when talking with Alok was that the `PNETCDF` issue would not be solved on betzy (or that no one was working to solve it) - @monsieuralok please correct me if I'm wrong. So we don't have an option to test for this bug on betzy.

I think the pnetcdf option should still work on Fram. Just now I was trying to do a meson build of BLOM/iHAMOCC on my own PC, but there seems to be too many things missing to test pnetcdf, so I was just about to start on Fram.

I can start by pulling a version before the explicit use statements were introduced and compare with one afterwards. This should give us a indication. Will post on this issue once I have some progress.

**Comment by jmaerz** [comment]
Ok, I see. After re-reading the compilation error of Dirk and looking deeper into the code, we miss to import `i0,ii,jj,j0,jj` (and potentially some others)  from `mod_xc` in `read_netcdf_var.F90`. I need to check the other files, where `PNETCDF` is used, though. Shall we branch from the milestone branch to fix this?

**Comment by TomasTorsvik** [comment]
`master` and `release-1.3` currently point to the same commit (98ade59), so it doesn't matter which one to branch from. It would be good to make a separate bugfix branch from 98ade59 and merge into `master` and `release-1.3` respectivesly, when we have fixed the bug.

**Comment by TomasTorsvik** [comment]
By the way, I have reproduced the bug on Fram. The machine settings on Fram use pnetcdf by default.
