### ISSUE TITLE
BLOM is not compiling in DEBUG mode

### ISSUE THREAD

**Issue by mvertens** [NorESMhub/BLOM#254]
I am getting the following errors when compiling BLOM in DEBUG model without  carbon isotopes 

```
mo_param1_bgc.F90(264): error #5561: Subscript #1 of the array MAP_POR2OCTRA has value -1 which is less than the lower bound of 1
mo_param1_bgc.F90(265): error #5561: Subscript #1 of the array MAP_POR2OCTRA has value -1 which is less than the lower bound of 1
```

I believe that the fix would be to introduce the following (see the <= new lines)
```F90
#ifdef cisonew <=== new
        if(ipowc13 > 0) map_por2octra(ipowc13) = isco213
	if(ipowc14 > 0) map_por2octra(ipowc14) = isco214
#endif <=== new
```

I have verified that the code now compiles in DEBUG mode with this change.

**Comment by JorgSchwinger** [comment]
This looks to me like a bug in the -C option of the intel compiler: The subscript has the value -1 according to the error message, this is why the statement `map_por2octra(ipowc13) = isco213` and the following one should never be reached (if carbon isotopes are deactivated).

Anyway, to work around this, I am fine with introducing the `#ifdef cisonew` here, although in this case I would suggest to also remove the `if(ipowc13 > 0)` and the if-statement in the following line, since this becomes redundant then.

**Comment by mvertens** [comment]
@JorgSchwinger - thanks for looking at this. 
I am perplexed as to why you think this is a bug in the compiler.
If you look at the defined dimensions in this case:
      INTEGER, PARAMETER :: i_pow_base=7
      INTEGER, PARAMETER :: i_pow_cisonew = 0
      INTEGER, PARAMETER :: npowtra = i_pow_base + i_pow_cisonew
      INTEGER, SAVE      :: map_por2octra(npowtra)
This implies that the minimum lower bound of map_por2octra is 1 - and we are trying to reference the -1 element which is outside the bounds. In DEBUG mode we compile with no optimization and add a -check bounds flag to the compilation so that at run time bounds checking is turned on. So I think the compiler is doing the right thing.

**Comment by JorgSchwinger** [comment]
Yes, that is all fine, but `ipowc13=-1` implies that `if(ipowc13 > 0)` is false, so the actual statement the error message originates from cannot be reached in the case that carbon isotopes are deactivated (and if they were activated  ipowc13 would have a valid value).

**Comment by mvertens** [comment]
@JorgSchwinger - you are right. Sorry about that. I was misreading the code.
