### ISSUE TITLE
Add output for actually used atmopheric pCO2 and pCO2 water vapour correction

### ISSUE THREAD

**Issue by JorgSchwinger** [NorESMhub/BLOM#31]
Atmospheric CO2 mixing ratio in the gas exchange formulation is modified by sea level pressure and a water vapour correction in the gas exchange formulation, but these are not in the output, so the true Delta pCO2 used cannot be traced.

**Comment by jmaerz** [comment]
@JorgSchwinger , in the course of the N cycle developments #147 , I am currently looking into the `carchm.F90` routine to get not only the fluxes (which are implemented), but also DpX (X being relevant gases). Maybe it would be a good time to shortly discuss the issue and we/I can implement the output.

**Comment by jmaerz** [comment]
As far as I understand it, we would like to have in addition to the dry air formulation
```
pco2d(i,j)=cu*1e6/Khd
```
(l. 520, `carchm.F90`) also something like
```
pco2m(i,j)=cu*1e6/Kh
```
for moist air, equivalent to the used `pco2` (l. 289, `carchm.F90`). So essentially using `Kh` (moist air) instead of `Khd` (dry air) -see `carchm_kequi.F90`- for the output for partial pressure of CO2 under moist air conditions. In case of a difference (DpCO2), one would then use a difference between `pco2m` and air concentration `atco2`. Please correct me, if I am wrong.

**Comment by JorgSchwinger** [comment]
I'm actually not sure what is "correct" to use for DpCO2. I think the partial pressure w.r.t. dry air is often used for this, even if it is corrected for water vapor in the flux calculations. It is in any case good to have both fields in the output. 

What I meant over lunch today: In carchm (line 526):
`kwco2sol(i,j) = kwco2*Kh*1e-6`
it is the product of Kw (piston velocity) and solubility that is saved for later output. This variable gets the name "KW" in the output files, which is misleading. I think it would be better to save KW and alpha (solubility) separately.

**Comment by jmaerz** [comment]
Ok, thanks. I'll try to take care of this by the end of the week.

**Comment by jmaerz** [comment]
Hi @JorgSchwinger , how save would it be to use the same name `kwco2` for the piston velocity only (and to avoid confusion)? Otherwise, I would suggest to implement/rename the following output:
- `pkwco2`     - Piston velocity for CO2
- `pkwco2khm` - Piston velocity times solubility corrected for moist air (replaces current `kwco2`)
- `khco2m`       - solubility constant corrected for moist air
- `pco2m`      - water pCO2 under moist air assumption
- `pco2d`       - water pCO2 under dry air assumption (replaces current `pco2`)
- `Dpco2`       - partial pressure difference between `pco2m` and `atco2`(?)
For the latter, I hope for more insights ... Or shall we even extend the list to `Dpco2m` and `Dpco2d` (+`khco2d`)?

**Comment by JorgSchwinger** [comment]
Hi Joeran, 

after thinking a bit about it, I believe the main variable pCO2 w.r.t. dry air (that is what is measured in the atmosphere). The method of the Weiss and Price 1980 paper is a bit special (incorporating the water vapor correction in the fit for solubility), at least I haven't seen it elsewhere. Usually, the water vapor correction is kept separate, and this is actually the more convenient way if you want to apply the same correction to all gases. From my perspective, the only "moist" thing we should add to the output is the corrected pCO2. Then, we have the quantity actually used in the flux calculations, and are able to infer the applied correction. For all other things (piston velocity, solubility, DpCO2), I believe, it is sufficient to have the "normal dry" output, since this is what is usually reported (as far as I am aware is, maybe Friderieke and Meike have different insights). Finally: Please don't rename pCO2!
