### ISSUE TITLE
Transition from "cgs" to "mks" as default for NorESM2.3?

### ISSUE THREAD

**Issue by TomasTorsvik** [NorESMhub/BLOM#338]
@matsbn , @jmaerz , @JorgSchwinger , @milicak 
As far as I know, we now have equivalent output for the "mks" and "cgs" units. Would it make sense to transition to "mks" as default for the upcoming NorESM2.3 release?

TODO:
- [x] Run coupled tests with interactive DMS to verify climatological similarity
- [x] Modify restart system: continue runs using MKS that have been started with CGS

**Comment by jmaerz** [comment]
Since `mks` will be at some point the new default, I have no objections. I would keep the `cgs` switch for NorESM2.3 (a t least as optional) though to document the transition.

**Comment by matsbn** [comment]
We should run some coupled tests (with interactive DMS at least) to verify climatological similarity, both with hybrid and isopycnic coordinate. Another thing missing is the ability to restart from a simulation with CGS units and continue with MKS units. Although a bit-reproducible restart is unlikely, I think it would be a useful functionality.

**Comment by matsbn** [comment]
I ran two coupled experiments, N1850frc2_cgs_20240502 and N1850frc2_mks_20240502, using the NorESM 2.0.6 codebase, but with current BLOM master (https://github.com/NorESMhub/BLOM/commit/9b3fcc171b3042733299e049371ec582bb4adfe6). Compset is N1850frc2 and grid combination f09_tn14. The latter experiment only differ by `./xmlchange BLOM_UNIT=mks`. I only ran for 10 years from initial conditions, and diagnostics for years 6-10 can be found here:

https://ns1012k.web.sigma2.no/diagnostics/noresm/matsbn/N1850frc2_cgs_20240502/
https://ns1012k.web.sigma2.no/diagnostics/noresm/matsbn/N1850frc2_mks_20240502/

The simulations compare quite well and I could not find anything that I think obviously stands out from internal variability. As an example, below is the DMS flux from the two simulations that I believe should aggregate quite some differences if there were severe unit issues.

Great with someone can have look and see if there is anything suspicious. The experiments could of course be extended to average out more of the internal variability, so suggestions/recommendations on that are welcome. In hindsight I should have run this with f19 resolution, since atm/lnd resolution should not matter here.

![](https://ns1012k.web.sigma2.no/diagnostics/noresm/matsbn/N1850frc2_cgs_20240502/HAMOCC_DIAG/yrs6to10-obs/set2/set2_ann_dmsflux_1model.png)

![](https://ns1012k.web.sigma2.no/diagnostics/noresm/matsbn/N1850frc2_mks_20240502/HAMOCC_DIAG/yrs6to10-obs/set2/set2_ann_dmsflux_1model.png)

**Comment by jmaerz** [comment]
Dear @matsbn , I skimmed through the iHAMOCC results and didn't see anything obviously wrong. Given that @JorgSchwinger was testing the `cgs` and `mks` settings after #233 and #334 , the iHAMOCC internals should work as expected. Since iHAMOCC internally, units haven't changed, I would also expect the restart to function even when moving from `cgs` to `mks`, but maybe I am missing something @JorgSchwinger and @TomasTorsvik?

**Comment by TomasTorsvik** [comment]
Hi @matsbn , @jmaerz , @JorgSchwinger , I have also looked through the iHAMOCC plots and I don't see anything that looks suspicious. I think we can check off that we have climotological similarity between `cgs` and `mks`.

**Comment by JorgSchwinger** [comment]
I also do not see anything suspicious in the HAMOCC diagnostics, everything looks seems to be in the range that can be expected from internal variability.

Regarding the restart capabilities, I agree it would be really useful to be able to restart from cgs restart files! I also concur with Jöran that as far as HAMOCC is concerned, there is no need for action (HAMMOC units have always been mks).
