### ISSUE TITLE
Compilation fails with current BLOM master

### ISSUE THREAD

**Issue by JorgSchwinger** [NorESMhub/BLOM#363]
@jmaerz @TomasTorsvik @mvertens  When I try to compile NorESM release 2.1.1 with current BLOM master, I get an error:

The number of actual arguments cannot be greater than the number of dummy arg
uments.   [INI_PARAMBGC]
    call ini_parambgc(idm,jdm)

which is correct, since the routine in `hamocc_ini` is indeed called with these arguments, while `ini_parambgc` has no argumnents.

I am confused: Isn't the compilation tested in regression and continuous integration testing? Did I do something stupid when checking the model out?

**Comment by mvertens** [comment]
@JorgSchwinger - you did nothing stupid. This is definitely a bug and is fixed in #362 and I believe is my fault.
I am responsible for changing the arguments to subroutine ini_parambgc() - and not fixing the call in mo_hamocc_init.
I'm not sure how this arose - but betzy being down has made testing difficult. But I don't understand why this did not get flagged in regression testing. Its still hard to test on betzy - so I'm not sure how to get this #362 tested and merged to master.
