### ISSUE TITLE
Write HAMOCC initial condition files to blom.input_data_list

### ISSUE THREAD

**Issue by JorgSchwinger** [NorESMhub/BLOM#37]
HAMOCC initial condition files need to be written to blom.input_data_list also for runtype/=STARTUP. The model attempts to read them in any case so they need to be present/downloaded. This will resolve https://github.com/NorESMhub/NorESM/issues/149

@matsbn @TomasTorsvik we need to discuss where to put these kind of changes now. Certainly into the master branch (but then master should first be synchronised with the release-1.0 branch). But probably also into release-1.0, since this will be a candidate included in future minor releases?

**Comment by TomasTorsvik** [comment]
@JorgSchwinger @matsbn 
At the moment the code base in "master" and release-1.0 branch are identical (see output from "git diff 84fd939 a8a7e94") but their commit history are different. Going on with commits to master should be fine, and I think updates to the release-1.0 should only be bug fixes from now on. The release tag itself should not be changed, so we should probably make new minor releases on the release-1.0 branch in coordination with NorESM minor releases. If the master branch develops with a mixture of bug fixes and feature developments, I think it should still be possible to "cherry pick" bug fix commits/pull requests from master to the release-1.0 branch, as long as the pull requests do not involve any feature changes as well.

**Comment by matsbn** [comment]
I think this is a kind of bug fix that should be a patch of release 1.0 and be available in tag v1.0.1 (see https://github.com/NorESMhub/BLOM/issues/19). There is another bug (https://github.com/NorESMhub/BLOM/issues/38) that could also be fixed in v1.0.1. Bug fixes of the 1.0 release should end up as commits in the release-1.0 branch and then tags v1.0.x of this branch are created (we don't create a persistent e.g. release-1.0.1 branch). Typically the bug fixes should be carried forward in the master branch also. As @TomasTorsvik mentions, master and release-1.0 branches are currently identical (code-wise). I do not have a strong opinion whether the bug fix is first committed in master or release-1.0 and cherry-picked to the other branch. In https://github.com/NorESMhub/BLOM/issues/19 I indicate arrows both ways between master and release branches.

**Comment by TomasTorsvik** [comment]
Should we add this bug fix to the release-1.0 branch already now? I don't see any reason to wait. We don't need to create a new tag right away, this can probably wait until next minor release of NorESM2.

It's also a question if we want to merge master to release-1.0 or just the bug fix. I think the way to do it is to cherry-pick the commit from Jörg's branch to the release-1.0 branch. I can test this on my own fork first to see how it works.

**Comment by TomasTorsvik** [comment]
I tested the cherry-pick option on my fork, you can see the result on
https://github.com/TomasTorsvik/BLOM-TTfork/network
(compare to https://github.com/NorESMhub/BLOM/network )

The exact same commit as Jörg made has been copied over to the release-1.0 branch, but there is no indication to show the connection between these commits in the repo tree as I can see.

**Comment by JorgSchwinger** [comment]
I think we only want bug fixes and possibly ports to other machines in subsequent minor releases, don't we? So cherry-picking this commit sounds right to me, and it looks like it does what it is supposed to do.

**Comment by TomasTorsvik** [comment]
In this case it might be the best option. However, I have been reading up a bit on what others are doing, and it seems that cherry-picking is frowned upon in general due to the risk of strange conflicts. This can happen if e.g. a bug fix works in master due to a commit that was introduced after master and release-1.0 split, so cherry-picking a single commit would not work in that case. We should probably discuss this together with Mats.

I will create a pull request with the cherry-picked commit, but I think I will create a new branch for it first, so I don't mess up my own repo too much.

**Comment by matsbn** [comment]
I think cherry-picking bug-fixes is fine from master to release branch. It seems to be a common procedure for trunk based development (see https://trunkbaseddevelopment.com/youre-doing-it-wrong/) as we mostly follow in the BLOM repository. I also would like to cherry-pick the bug-fix in commit https://github.com/NorESMhub/BLOM/commit/13babb14c75d7681edf8c56d10887d576b3b7412 into the release-1.0 branch. When master and release branches have diverged to the point cherry-picking will cause many conflicts, I think bug-fixes must be done by separate commits.

**Comment by TomasTorsvik** [comment]
Thanks @matsbn, interesting read. I guess the the point is that cherry-picking can be OK from master to release branch, since the release branch should never be re-merged with master. In that case there is of course no risk of merge conflicts.
