### ISSUE TITLE
Use omask from mo_intfcblom consitently in iHAMOCC

### ISSUE THREAD

**Issue by TomasTorsvik** [NorESMhub/BLOM#94]
The ocean mask variable "omask" is defined in mo_intfcblom, but is still passed as a variable in subroutine calls. I assume the intention is to replace these calls with something like
use mo_intfcblom, only: omask
@JorgSchwinger are you working on this, or should I go ahead and try to implement this?

**Comment by JorgSchwinger** [comment]
No, the intention here is to separate the core iHAMOOC (everything below the HAMOCC4BCM call) from the interface with the physical ocean model. Since BLOM does not use an ocean-mask which could be passed directly, we have to rely on this intermediate variable which is defined in the BLOM-iHAMOCC interface but then passed as a argument to the core iHAMOCC.

This should stay as it is.

**Comment by TomasTorsvik** [comment]
OK. I couldn't figure out why it was defined in a module and passed as an argument, but I will leave it alone then.
